/// <reference types="babel-plugin-text-break-resolver" />

// NOTE: This file should not be edited and should be committed with your source code.
// It is auto-generated by babel-plugin-text-break-resolver.
