const { isNodeModules } = require('./utils');
const { writeSummary } = require('./report');
const fs = require('fs');
const path = require('path');

// Build state (accumulates across all transforms in a build)
let buildState = null;
let buildId = null;

const DEFAULT_CONFIG = {
  numberOfLines: false,
  adjustsFontSizeToFit: false,
  trailingSpaces: true,
};

const DEFAULT_BUFFER_MODE = 'end';
const VALID_BUFFER_MODES = new Set(['none', 'start', 'end', 'both']);

function generateEnvTypes(cwd) {
  if (!cwd) return;
  const envFilePath = path.join(cwd, 'text-break-env.d.ts');
  if (!fs.existsSync(envFilePath)) {
    const content = `/// <reference types="babel-plugin-text-break-resolver" />

// NOTE: This file should not be edited and should be committed with your source code. It is auto-generated by babel-plugin-text-break-resolver.
`;
    try {
      fs.writeFileSync(envFilePath, content, 'utf8');
    } catch (e) {
      // Ignore write errors silently to not crash the bundler
    }
  }
}

function isJsxIdentifier(node) {
  return node && node.type === 'JSXIdentifier';
}

function getJsxName(node) {
  if (!node || !isJsxIdentifier(node)) return null;
  return node.name;
}

function getLiteralValue(node) {
  if (!node) return null;
  if (node.type === 'StringLiteral') return node.value;
  if (node.type === 'BooleanLiteral') return node.value;
  if (node.type === 'NumericLiteral') return node.value;
  if (node.type === 'NullLiteral') return null;
  if (node.type === 'JSXExpressionContainer') return getLiteralValue(node.expression);
  if (node.type === 'TemplateLiteral' && node.expressions.length === 0) {
    return node.quasis.map((quasi) => quasi.value.cooked ?? quasi.value.raw).join('');
  }
  return null;
}

function getStaticClassTokens(node) {
  const value = getLiteralValue(node);
  if (typeof value !== 'string') return [];
  return value.trim().split(/\s+/).filter(Boolean);
}

function mergeStyleInfo(target, source) {
  if (!source) return target;
  if (source.textAlign != null) target.textAlign = source.textAlign;
  if (source.alignItems != null) target.alignItems = source.alignItems;
  if (source.justifyContent != null) target.justifyContent = source.justifyContent;
  if (source.flexDirection != null) target.flexDirection = source.flexDirection;
  if (source.classTokens && source.classTokens.length > 0) {
    target.classTokens = Array.from(new Set([...(target.classTokens || []), ...source.classTokens]));
  }
  return target;
}

function resolveStaticStyle(node) {
  if (!node) return null;

  if (node.type === 'JSXExpressionContainer') {
    return resolveStaticStyle(node.expression);
  }

  if (node.type === 'ArrayExpression') {
    return node.elements.reduce((acc, element) => {
      if (!element) return acc;
      return mergeStyleInfo(acc, resolveStaticStyle(element));
    }, {});
  }

  if (node.type === 'ObjectExpression') {
    return node.properties.reduce((acc, property) => {
      if (property.type !== 'ObjectProperty') return acc;
      if (property.computed) return acc;
      const key = property.key.type === 'Identifier'
        ? property.key.name
        : property.key.type === 'StringLiteral'
          ? property.key.value
          : null;
      if (!key) return acc;

      const value = getLiteralValue(property.value);
      if (value == null) return acc;

      if (key === 'textAlign' || key === 'alignItems' || key === 'justifyContent' || key === 'flexDirection') {
        acc[key] = value;
      }

      return acc;
    }, {});
  }

  return null;
}

function resolveTextAlignHint(attributes) {
  let resolved = {};

  for (const attr of attributes) {
    if (attr.type !== 'JSXAttribute' || !attr.name) continue;

    const attrName = attr.name.name;
    if (attrName !== 'style' && attrName !== 'className') continue;

    if (attrName === 'className') {
      const classTokens = getStaticClassTokens(attr.value);
      if (classTokens.length > 0) {
        resolved.classTokens = Array.from(new Set([...(resolved.classTokens || []), ...classTokens]));
      }
      continue;
    }

    const styleInfo = resolveStaticStyle(attr.value);
    resolved = mergeStyleInfo(resolved, styleInfo);
  }

  return resolved;
}

function hasClassToken(info, token) {
  return Boolean(info && info.classTokens && info.classTokens.includes(token));
}

function classifyTextMode(info) {
  if (!info) return null;

  if (info.textAlign === 'center' || (hasClassToken(info, 'text-center'))) return 'both';
  if (info.textAlign === 'left' || hasClassToken(info, 'text-left')) return 'end';
  if (info.textAlign === 'right' || hasClassToken(info, 'text-right')) return 'start';

  const centeredLayout =
    (info.alignItems === 'center' && info.justifyContent === 'center') ||
    (hasClassToken(info, 'items-center') && hasClassToken(info, 'justify-center'));

  if (centeredLayout) return 'both';

  return null;
}

function isWhitespaceJsxText(node) {
  return node && node.type === 'JSXText' && node.value.trim() === '';
}

function isReactNativeTextName(name, state) {
  if (!name) return false;
  if (state.rnTextNames && state.rnTextNames.has(name)) return true;
  return name === 'Text';
}

function isTextLikeElement(node, state) {
  if (!node || node.type !== 'JSXElement') return false;
  const name = getJsxName(node.openingElement && node.openingElement.name);
  return isReactNativeTextName(name, state);
}

function getMeaningfulJsxChildren(node) {
  if (!node || !node.children) return [];
  return node.children.filter((child) => {
    if (!child) return false;
    if (isWhitespaceJsxText(child)) return false;
    if (child.type === 'JSXExpressionContainer' && child.expression && child.expression.type === 'JSXEmptyExpression') {
      return false;
    }
    return true;
  });
}

function isSpaceDistributedLayout(info) {
  if (!info) return false;
  const classTokens = info.classTokens || [];
  return (
    classTokens.includes('justify-between') ||
    classTokens.includes('justify-around') ||
    classTokens.includes('justify-evenly') ||
    info.justifyContent === 'space-between' ||
    info.justifyContent === 'space-around' ||
    info.justifyContent === 'space-evenly'
  );
}

function isDistributedLayout(info) {
  if (!info) return false;
  const classTokens = info.classTokens || [];
  return (
    info.flexDirection === 'row' ||
    classTokens.includes('flex-row') ||
    isSpaceDistributedLayout(info)
  );
}

function tagDistributedChildren(path) {
  if (path.node._checkedDistributedLayout) return;
  path.node._checkedDistributedLayout = true;

  if (!path.isJSXElement()) return;
  const info = resolveTextAlignHint(path.node.openingElement.attributes);
  if (!isSpaceDistributedLayout(info)) return;

  const meaningful = getMeaningfulJsxChildren(path.node);
  if (meaningful.length === 0) return;

  if (meaningful.length === 1) {
    meaningful[0]._distributedPosition = 'first';
    return;
  }

  meaningful[0]._distributedPosition = 'first';
  meaningful[meaningful.length - 1]._distributedPosition = 'last';
  for (let i = 1; i < meaningful.length - 1; i++) {
    meaningful[i]._distributedPosition = 'middle';
  }
}

function hasCenteredStackSignal(info) {
  if (!info) return false;
  const classTokens = info.classTokens || [];
  return (
    info.alignItems === 'center' ||
    info.justifyContent === 'center' ||
    classTokens.includes('items-center') ||
    classTokens.includes('self-center') ||
    classTokens.includes('justify-center')
  );
}

function isCenteredStackContainer(path, state) {
  if (!path.isJSXElement()) return false;

  const info = resolveTextAlignHint(path.node.openingElement.attributes);
  if (classifyTextMode(info) === 'both') return true;
  if (!hasCenteredStackSignal(info) || isDistributedLayout(info)) return false;

  const meaningfulChildren = getMeaningfulJsxChildren(path.node);
  if (meaningfulChildren.length === 0) return false;

  let textLikeChildren = 0;
  for (const child of meaningfulChildren) {
    if (child.type === 'JSXText') {
      if (child.value.trim().length > 0) {
        textLikeChildren++;
      }
      continue;
    }

    if (child.type === 'JSXExpressionContainer') {
      const expression = child.expression;
      if (!expression || expression.type === 'JSXEmptyExpression') {
        continue;
      }
      if (expression.type === 'StringLiteral' || expression.type === 'NumericLiteral' || expression.type === 'TemplateLiteral' || expression.type === 'Identifier' || expression.type === 'MemberExpression' || expression.type === 'LogicalExpression' || expression.type === 'ConditionalExpression') {
        textLikeChildren++;
        continue;
      }
      return false;
    }

    if (child.type === 'JSXElement') {
      if (isTextLikeElement(child, state)) {
        textLikeChildren++;
        continue;
      }
      return false;
    }

    return false;
  }

  return textLikeChildren > 0;
}

function getCurrentTextMode(path, state) {
  const openingElement = path.node.openingElement;
  const textInfo = resolveTextAlignHint(openingElement.attributes);
  const directMode = classifyTextMode(textInfo);
  if (directMode) return directMode;

  if (path.node._distributedPosition === 'first') return 'end';
  if (path.node._distributedPosition === 'last') return 'start';
  if (path.node._distributedPosition === 'middle') return 'both';

  let current = path.parentPath;
  while (current) {
    if (current.isJSXElement()) {
      const ancestorInfo = resolveTextAlignHint(current.node.openingElement.attributes);
      const ancestorMode = classifyTextMode(ancestorInfo);
      if (ancestorMode) return ancestorMode;
      
      if (current.node._distributedPosition === 'first') return 'end';
      if (current.node._distributedPosition === 'last') return 'start';
      if (current.node._distributedPosition === 'middle') return 'both';

      if (current.node._checkedCenteredStack === undefined) {
        current.node._isCenteredStack = isCenteredStackContainer(current, state);
        current.node._checkedCenteredStack = true;
      }

      if (current.node._isCenteredStack) return 'both';
    }
    current = current.parentPath;
  }

  return DEFAULT_BUFFER_MODE;
}

function getBufferNodes(t, mode) {
  if (mode === 'none') return [];
  const buffer = t.jsxExpressionContainer(t.stringLiteral('  '));
  if (mode === 'start') return [buffer];
  if (mode === 'both') {
    return [
      t.jsxExpressionContainer(t.stringLiteral('  ')),
      t.jsxExpressionContainer(t.stringLiteral('  ')),
    ];
  }
  return [buffer];
}

function getTextBreakBufferOverride(attributes) {
  let explicitMode = null;
  let sawTextBreakBuffer = false;
  let sawNoTrailingSpaces = false;
  const removeIndices = [];

  for (let i = 0; i < attributes.length; i++) {
    const attr = attributes[i];
    if (attr.type !== 'JSXAttribute' || !attr.name) continue;

    const attrName = attr.name.name;
    if (attrName === 'noTrailingSpaces') {
      removeIndices.push(i);
      sawNoTrailingSpaces = true;
      continue;
    }

    if (attrName === 'textBreakBuffer') {
      removeIndices.push(i);
      sawTextBreakBuffer = true;
      const rawValue = getLiteralValue(attr.value);
      if (typeof rawValue === 'string' && VALID_BUFFER_MODES.has(rawValue)) {
        explicitMode = rawValue;
      } else {
        explicitMode = 'none';
      }
    }
  }

  if (!sawTextBreakBuffer && sawNoTrailingSpaces) {
    explicitMode = 'none';
  }

  return { explicitMode, hasExplicitMode: explicitMode != null, removeIndices };
}

function buildAttrsToAdd(config) {
  const attrs = [
    { name: 'textBreakStrategy', value: 'simple', type: 'string' },
  ];

  if (config.numberOfLines) {
    attrs.push({ name: 'numberOfLines', value: 1, type: 'number' });
  }
  if (config.adjustsFontSizeToFit) {
    attrs.push({ name: 'adjustsFontSizeToFit', value: true, type: 'boolean' });
  }

  return attrs;
}

function initBuild() {
  if (!buildId) {
    buildId = Date.now().toString(36).toUpperCase();
    buildState = {
      id: buildId,
      startTime: new Date().toISOString(),
      files: new Map(),
      seenLocations: new Set(),
      counts: {
        textFound: 0,
        textBreakStrategy: 0,
        numberOfLines: 0,
        adjustsFontSizeToFit: 0,
        bufferStart: 0,
        bufferEnd: 0,
        bufferBoth: 0,
        bufferNone: 0,
      },
    };
  }
  return buildState;
}

function addBufferChildren(path, t, mode) {
  if (!mode || mode === 'none') return [];
  const nodes = getBufferNodes(t, mode);
  if (nodes.length === 0) return [];

  if (mode === 'start') {
    path.node.children.unshift(nodes[0]);
    return ['bufferStart'];
  }

  if (mode === 'both') {
    path.node.children.unshift(nodes[0]);
    path.node.children.push(nodes[1]);
    return ['bufferBoth'];
  }

  path.node.children.push(nodes[0]);
  return ['bufferEnd'];
}

module.exports = function (babel) {
  const { types: t } = babel;

  function recordBuildChange(state2, filename, line, col, added, sourceCode) {
    if (!state2.files.has(filename)) {
      state2.files.set(filename, []);
    }
    state2.files.get(filename).push({ line, col, added, sourceCode });
  }

  function registerReactNativeImports(path, state) {
    const textNames = new Set(['Text']);

    path.traverse({
      ImportDeclaration(importPath) {
        if (importPath.node.source.value !== 'react-native') return;

        for (const specifier of importPath.node.specifiers) {
          if (specifier.type !== 'ImportSpecifier') continue;
          const importedName = specifier.imported && specifier.imported.name;
          const localName = specifier.local && specifier.local.name;
          if (!importedName || !localName) continue;

          if (importedName === 'Text') {
            textNames.add(localName);
          }
        }
      },
    });

    state.rnTextNames = textNames;
  }

  return {
    name: 'text-break-strategy',

    pre(api) {
      this.pluginConfig = Object.assign({}, DEFAULT_CONFIG, api.options);
      this.rnTextNames = null;

      try {
        generateEnvTypes(process.cwd());
      } catch (e) {
        // Safe fail
      }
    },

    visitor: {
      Program: {
        enter(path, state) {
          registerReactNativeImports(path, state);
        },
      },

      JSXElement(path, state) {
        tagDistributedChildren(path);

        if (path.node._checkedCenteredStack === undefined) {
          path.node._isCenteredStack = isCenteredStackContainer(path, state);
          path.node._checkedCenteredStack = true;
        }

        const openingElement = path.node.openingElement;
        const elementName = getJsxName(openingElement.name);

        if (!isReactNativeTextName(elementName, state)) return;
        if (openingElement.selfClosing) return;

        const filename = state.filename || 'unknown';
        if (isNodeModules(filename)) return;

        const state2 = initBuild();
        const loc = path.node.loc;
        const line = loc.start.line;
        const col = loc.start.column;
        const locationKey = `${filename}:${line}:${col}`;

        if (state2.seenLocations.has(locationKey)) return;
        state2.seenLocations.add(locationKey);

        state2.counts.textFound++;

        const attrs = openingElement.attributes;
        const existingAttrs = new Set();
        for (let i = 0; i < attrs.length; i++) {
          const attr = attrs[i];
          if (attr.type === 'JSXAttribute' && attr.name) {
            existingAttrs.add(attr.name.name);
          }
        }

        const override = getTextBreakBufferOverride(attrs);
        if (override.removeIndices.length > 0) {
          const indices = override.removeIndices.slice().sort((a, b) => b - a);
          for (const index of indices) {
            attrs.splice(index, 1);
          }
        }

        const attrsToAdd = buildAttrsToAdd(this.pluginConfig);
        const toAdd = [];
        for (let i = 0; i < attrsToAdd.length; i++) {
          const attrDef = attrsToAdd[i];
          if (!existingAttrs.has(attrDef.name)) {
            toAdd.push(attrDef);
            switch (attrDef.name) {
              case 'textBreakStrategy':
                state2.counts.textBreakStrategy++;
                break;
              case 'numberOfLines':
                state2.counts.numberOfLines++;
                break;
              case 'adjustsFontSizeToFit':
                state2.counts.adjustsFontSizeToFit++;
                break;
            }
          }
        }

        if (toAdd.length === 0 && !this.pluginConfig.trailingSpaces) return;

        for (let i = 0; i < toAdd.length; i++) {
          const attrDef = toAdd[i];
          let literalValue;

          if (attrDef.type === 'boolean') {
            literalValue = t.booleanLiteral(attrDef.value);
          } else if (attrDef.type === 'number') {
            literalValue = t.numericLiteral(attrDef.value);
          } else {
            literalValue = t.stringLiteral(attrDef.value);
          }

          attrs.push(t.jSXAttribute(t.jSXIdentifier(attrDef.name), t.jsxExpressionContainer(literalValue)));
        }

        const added = toAdd.map((attr) => attr.name);

        if (this.pluginConfig.trailingSpaces) {
          const bufferMode = override.hasExplicitMode ? override.explicitMode : getCurrentTextMode(path, state);
          const bufferFlags = addBufferChildren(path, t, bufferMode);
          if (bufferFlags.length > 0) {
            for (const flag of bufferFlags) {
              state2.counts[flag]++;
              added.push(flag);
            }
          } else {
            state2.counts.bufferNone++;
            added.push('bufferNone');
          }
        }

        const sourceCode = (path.hub && path.hub.file && path.hub.file.code) || '';
        recordBuildChange(state2, filename, line, col, added, sourceCode);
      },
    },
  };
};

process.on('exit', () => {
  if (buildState) {
    try {
      writeSummary(buildState);
    } catch (e) {}
  }
});
